<?php
 return array (
  'logo' => NULL,
  'force_https' => '0',
  'stop_register' => '0',
  'app_name' => '$APP_NAME',
  'app_description' => '$APP_DESCIPTION',
  'app_url' => '$PUBLIC_APP_URL',
  'subscribe_url' => $SUBSCRIPT_URL,
  'try_out_plan_id' => '2',
  'try_out_hour' => '24',
  'tos_url' => NULL,
  'currency' => '$APP_CURRENCY',
  'currency_symbol' => '$APP_CURRENCY_SYMBOL',
  'email_whitelist_enable' => '0',
  'email_whitelist_suffix' => 
  array (
    0 => 'gmail.com',
    1 => 'qq.com',
    2 => '163.com',
    3 => 'yahoo.com',
    4 => 'sina.com',
    5 => '126.com',
    6 => 'outlook.com',
    7 => 'yeah.net',
    8 => 'foxmail.com',
  ),
  'email_gmail_limit_enable' => '0',
  'recaptcha_enable' => '0',
  'recaptcha_key' => NULL,
  'recaptcha_site_key' => NULL,
  'email_verify' => '0',
  'safe_mode_enable' => '0',
  'register_limit_by_ip_enable' => '0',
  'register_limit_count' => '3',
  'register_limit_expire' => '60',
  'secure_path' => '${APP_SECURE_PATH}',
  'password_limit_enable' => '1',
  'password_limit_count' => '5',
  'password_limit_expire' => '60',
  'invite_force' => '0',
  'invite_commission' => '25',
  'invite_gen_limit' => '10',
  'invite_never_expire' => '1',
  'commission_first_time_enable' => '1',
  'commission_auto_check_enable' => '1',
  'commission_withdraw_limit' => '100',
  'commission_withdraw_method' => 
  array (
    0 => '支付宝',
    1 => 'USDT',
    2 => 'Paypal',
  ),
  'withdraw_close_enable' => '0',
  'commission_distribution_enable' => '0',
  'commission_distribution_l1' => NULL,
  'commission_distribution_l2' => NULL,
  'commission_distribution_l3' => NULL,
  'server_token' => 'ztLDsKh7hayRhXG2JEckhzbe',
  'server_pull_interval' => '60',
  'server_push_interval' => '60',
) ;
